---
- name: Configure YARN
  hosts: hadoop
  become: yes
  tasks:
    - name: Create YARN data directories
      file:
        path: "{{ item }}"
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'
      loop:
        - /home/hadoop/hadoop_data/yarn/local
        - /home/hadoop/hadoop_data/yarn/logs

    - name: Deploy yarn-site.xml
      template:
        src: templates/yarn-site.xml.j2
        dest: /home/hadoop/hadoop/etc/hadoop/yarn-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'

    - name: Deploy mapred-site.xml
      template:
        src: templates/mapred-site.xml.j2
        dest: /home/hadoop/hadoop/etc/hadoop/mapred-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'

    - name: Update environment variables for YARN
      blockinfile:
        path: /home/hadoop/.bashrc
        block: |
          export YARN_HOME=${HADOOP_HOME}
          export HADOOP_MAPRED_HOME=${HADOOP_HOME}
        marker: "# {mark} YARN ENVIRONMENT"
        create: yes
        owner: hadoop
        group: hadoop

- name: Start YARN services
  hosts: hadoop
  become: yes
  tasks:
    - name: Start ResourceManager (only on NameNode)
      shell: |
        source /home/hadoop/.bashrc
        /home/hadoop/hadoop/bin/yarn --daemon start resourcemanager
      become_user: hadoop
      when: inventory_hostname == 'team-22-nn'

    - name: Start NodeManagers (on all nodes)
      shell: |
        source /home/hadoop/.bashrc
        /home/hadoop/hadoop/bin/yarn --daemon start nodemanager
      become_user: hadoop

    - name: Start MapReduce JobHistory Server
      shell: |
        source /home/hadoop/.bashrc
        /home/hadoop/hadoop/bin/mapred --daemon start historyserver
      become_user: hadoop
      when: inventory_hostname == 'team-22-nn'

- name: Quick YARN check
  hosts: namenodes
  become: yes
  tasks:
    - name: Check YARN processes
      shell: |
        sudo -u hadoop jps | grep -E 'ResourceManager|NodeManager|JobHistoryServer'
      register: yarn_processes
    
    - name: Show YARN processes
      debug:
        msg: "{{ yarn_processes.stdout_lines }}"
    
    - name: Check if ResourceManager is listening
      shell: |
        sudo ss -tlnp | grep :8088 || echo "Port 8088 not listening"
      register: yarn_port
    
    - name: Show port status
      debug:
        msg: "{{ yarn_port.stdout }}"
